// Country Codes used to translate the locationNumber provided on-Chain to a ISO-Alpha2 string

export const countryCodes: { [index: string]: { alpha2: string; name: string } } = {
  "4": { alpha2: "AF", name: "Afghanistan" },
  "248": { alpha2: "AX", name: "Åland Islands" },
  "8": { alpha2: "AL", name: "Albania" },
  "12": { alpha2: "DZ", name: "Algeria" },
  "16": { alpha2: "AS", name: "American Samoa" },
  "20": { alpha2: "AD", name: "Andorra" },
  "24": { alpha2: "AO", name: "Angola" },
  "660": { alpha2: "AI", name: "Anguilla" },
  "10": { alpha2: "AQ", name: "Antarctica" },
  "28": { alpha2: "AG", name: "Antigua and Barbuda" },
  "32": { alpha2: "AR", name: "Argentina" },
  "51": { alpha2: "AM", name: "Armenia" },
  "533": { alpha2: "AW", name: "Aruba" },
  "36": { alpha2: "AU", name: "Australia" },
  "40": { alpha2: "AT", name: "Austria" },
  "31": { alpha2: "AZ", name: "Azerbaijan" },
  "44": { alpha2: "BS", name: "Bahamas" },
  "48": { alpha2: "BH", name: "Bahrain" },
  "50": { alpha2: "BD", name: "Bangladesh" },
  "52": { alpha2: "BB", name: "Barbados" },
  "112": { alpha2: "BY", name: "Belarus" },
  "56": { alpha2: "BE", name: "Belgium" },
  "84": { alpha2: "BZ", name: "Belize" },
  "204": { alpha2: "BJ", name: "Benin" },
  "60": { alpha2: "BM", name: "Bermuda" },
  "64": { alpha2: "BT", name: "Bhutan" },
  "68": { alpha2: "BO", name: "Bolivia (Plurinational State of)" },
  "535": { alpha2: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  "70": { alpha2: "BA", name: "Bosnia and Herzegovina" },
  "72": { alpha2: "BW", name: "Botswana" },
  "74": { alpha2: "BV", name: "Bouvet Island" },
  "76": { alpha2: "BR", name: "Brazil" },
  "86": { alpha2: "IO", name: "British Indian Ocean Territory" },
  "96": { alpha2: "BN", name: "Brunei Darussalam" },
  "100": { alpha2: "BG", name: "Bulgaria" },
  "854": { alpha2: "BF", name: "Burkina Faso" },
  "108": { alpha2: "BI", name: "Burundi" },
  "132": { alpha2: "CV", name: "Cabo Verde" },
  "116": { alpha2: "KH", name: "Cambodia" },
  "120": { alpha2: "CM", name: "Cameroon" },
  "124": { alpha2: "CA", name: "Canada" },
  "136": { alpha2: "KY", name: "Cayman Islands" },
  "140": { alpha2: "CF", name: "Central African Republic" },
  "148": { alpha2: "TD", name: "Chad" },
  "152": { alpha2: "CL", name: "Chile" },
  "156": { alpha2: "CN", name: "China" },
  "162": { alpha2: "CX", name: "Christmas Island" },
  "166": { alpha2: "CC", name: "Cocos (Keeling) Islands" },
  "170": { alpha2: "CO", name: "Colombia" },
  "174": { alpha2: "KM", name: "Comoros" },
  "178": { alpha2: "CG", name: "Congo" },
  "180": { alpha2: "CD", name: "Congo, Democratic Republic of the" },
  "184": { alpha2: "CK", name: "Cook Islands" },
  "188": { alpha2: "CR", name: "Costa Rica" },
  "384": { alpha2: "CI", name: "Côte d'Ivoire" },
  "191": { alpha2: "HR", name: "Croatia" },
  "192": { alpha2: "CU", name: "Cuba" },
  "531": { alpha2: "CW", name: "Curaçao" },
  "196": { alpha2: "CY", name: "Cyprus" },
  "203": { alpha2: "CZ", name: "Czechia" },
  "208": { alpha2: "DK", name: "Denmark" },
  "262": { alpha2: "DJ", name: "Djibouti" },
  "212": { alpha2: "DM", name: "Dominica" },
  "214": { alpha2: "DO", name: "Dominican Republic" },
  "218": { alpha2: "EC", name: "Ecuador" },
  "818": { alpha2: "EG", name: "Egypt" },
  "222": { alpha2: "SV", name: "El Salvador" },
  "226": { alpha2: "GQ", name: "Equatorial Guinea" },
  "232": { alpha2: "ER", name: "Eritrea" },
  "233": { alpha2: "EE", name: "Estonia" },
  "748": { alpha2: "SZ", name: "Eswatini" },
  "231": { alpha2: "ET", name: "Ethiopia" },
  "238": { alpha2: "FK", name: "Falkland Islands (Malvinas)" },
  "234": { alpha2: "FO", name: "Faroe Islands" },
  "242": { alpha2: "FJ", name: "Fiji" },
  "246": { alpha2: "FI", name: "Finland" },
  "250": { alpha2: "FR", name: "France" },
  "254": { alpha2: "GF", name: "French Guiana" },
  "258": { alpha2: "PF", name: "French Polynesia" },
  "260": { alpha2: "TF", name: "French Southern Territories" },
  "266": { alpha2: "GA", name: "Gabon" },
  "270": { alpha2: "GM", name: "Gambia" },
  "268": { alpha2: "GE", name: "Georgia" },
  "276": { alpha2: "DE", name: "Germany" },
  "288": { alpha2: "GH", name: "Ghana" },
  "292": { alpha2: "GI", name: "Gibraltar" },
  "300": { alpha2: "GR", name: "Greece" },
  "304": { alpha2: "GL", name: "Greenland" },
  "308": { alpha2: "GD", name: "Grenada" },
  "312": { alpha2: "GP", name: "Guadeloupe" },
  "316": { alpha2: "GU", name: "Guam" },
  "320": { alpha2: "GT", name: "Guatemala" },
  "831": { alpha2: "GG", name: "Guernsey" },
  "324": { alpha2: "GN", name: "Guinea" },
  "624": { alpha2: "GW", name: "Guinea-Bissau" },
  "328": { alpha2: "GY", name: "Guyana" },
  "332": { alpha2: "HT", name: "Haiti" },
  "334": { alpha2: "HM", name: "Heard Island and McDonald Islands" },
  "336": { alpha2: "VA", name: "Holy See" },
  "340": { alpha2: "HN", name: "Honduras" },
  "344": { alpha2: "HK", name: "Hong Kong" },
  "348": { alpha2: "HU", name: "Hungary" },
  "352": { alpha2: "IS", name: "Iceland" },
  "356": { alpha2: "IN", name: "India" },
  "360": { alpha2: "ID", name: "Indonesia" },
  "364": { alpha2: "IR", name: "Iran (Islamic Republic of)" },
  "368": { alpha2: "IQ", name: "Iraq" },
  "372": { alpha2: "IE", name: "Ireland" },
  "833": { alpha2: "IM", name: "Isle of Man" },
  "376": { alpha2: "IL", name: "Israel" },
  "380": { alpha2: "IT", name: "Italy" },
  "388": { alpha2: "JM", name: "Jamaica" },
  "392": { alpha2: "JP", name: "Japan" },
  "832": { alpha2: "JE", name: "Jersey" },
  "400": { alpha2: "JO", name: "Jordan" },
  "398": { alpha2: "KZ", name: "Kazakhstan" },
  "404": { alpha2: "KE", name: "Kenya" },
  "296": { alpha2: "KI", name: "Kiribati" },
  "408": { alpha2: "KP", name: "Korea (Democratic People's Republic of)" },
  "410": { alpha2: "KR", name: "Korea, Republic of" },
  "414": { alpha2: "KW", name: "Kuwait" },
  "417": { alpha2: "KG", name: "Kyrgyzstan" },
  "418": { alpha2: "LA", name: "Lao People's Democratic Republic" },
  "428": { alpha2: "LV", name: "Latvia" },
  "422": { alpha2: "LB", name: "Lebanon" },
  "426": { alpha2: "LS", name: "Lesotho" },
  "430": { alpha2: "LR", name: "Liberia" },
  "434": { alpha2: "LY", name: "Libya" },
  "438": { alpha2: "LI", name: "Liechtenstein" },
  "440": { alpha2: "LT", name: "Lithuania" },
  "442": { alpha2: "LU", name: "Luxembourg" },
  "446": { alpha2: "MO", name: "Macao" },
  "450": { alpha2: "MG", name: "Madagascar" },
  "454": { alpha2: "MW", name: "Malawi" },
  "458": { alpha2: "MY", name: "Malaysia" },
  "462": { alpha2: "MV", name: "Maldives" },
  "466": { alpha2: "ML", name: "Mali" },
  "470": { alpha2: "MT", name: "Malta" },
  "584": { alpha2: "MH", name: "Marshall Islands" },
  "474": { alpha2: "MQ", name: "Martinique" },
  "478": { alpha2: "MR", name: "Mauritania" },
  "480": { alpha2: "MU", name: "Mauritius" },
  "175": { alpha2: "YT", name: "Mayotte" },
  "484": { alpha2: "MX", name: "Mexico" },
  "583": { alpha2: "FM", name: "Micronesia (Federated States of)" },
  "498": { alpha2: "MD", name: "Moldova, Republic of" },
  "492": { alpha2: "MC", name: "Monaco" },
  "496": { alpha2: "MN", name: "Mongolia" },
  "499": { alpha2: "ME", name: "Montenegro" },
  "500": { alpha2: "MS", name: "Montserrat" },
  "504": { alpha2: "MA", name: "Morocco" },
  "508": { alpha2: "MZ", name: "Mozambique" },
  "104": { alpha2: "MM", name: "Myanmar" },
  "516": { alpha2: "NA", name: "Namibia" },
  "520": { alpha2: "NR", name: "Nauru" },
  "524": { alpha2: "NP", name: "Nepal" },
  "528": { alpha2: "NL", name: "Netherlands" },
  "540": { alpha2: "NC", name: "New Caledonia" },
  "554": { alpha2: "NZ", name: "New Zealand" },
  "558": { alpha2: "NI", name: "Nicaragua" },
  "562": { alpha2: "NE", name: "Niger" },
  "566": { alpha2: "NG", name: "Nigeria" },
  "570": { alpha2: "NU", name: "Niue" },
  "574": { alpha2: "NF", name: "Norfolk Island" },
  "807": { alpha2: "MK", name: "North Macedonia" },
  "580": { alpha2: "MP", name: "Northern Mariana Islands" },
  "578": { alpha2: "NO", name: "Norway" },
  "512": { alpha2: "OM", name: "Oman" },
  "586": { alpha2: "PK", name: "Pakistan" },
  "585": { alpha2: "PW", name: "Palau" },
  "275": { alpha2: "PS", name: "Palestine, State of" },
  "591": { alpha2: "PA", name: "Panama" },
  "598": { alpha2: "PG", name: "Papua New Guinea" },
  "600": { alpha2: "PY", name: "Paraguay" },
  "604": { alpha2: "PE", name: "Peru" },
  "608": { alpha2: "PH", name: "Philippines" },
  "612": { alpha2: "PN", name: "Pitcairn" },
  "616": { alpha2: "PL", name: "Poland" },
  "620": { alpha2: "PT", name: "Portugal" },
  "630": { alpha2: "PR", name: "Puerto Rico" },
  "634": { alpha2: "QA", name: "Qatar" },
  "638": { alpha2: "RE", name: "Réunion" },
  "642": { alpha2: "RO", name: "Romania" },
  "643": { alpha2: "RU", name: "Russian Federation" },
  "646": { alpha2: "RW", name: "Rwanda" },
  "652": { alpha2: "BL", name: "Saint Barthélemy" },
  "654": { alpha2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
  "659": { alpha2: "KN", name: "Saint Kitts and Nevis" },
  "662": { alpha2: "LC", name: "Saint Lucia" },
  "663": { alpha2: "MF", name: "Saint Martin (French part)" },
  "666": { alpha2: "PM", name: "Saint Pierre and Miquelon" },
  "670": { alpha2: "VC", name: "Saint Vincent and the Grenadines" },
  "882": { alpha2: "WS", name: "Samoa" },
  "674": { alpha2: "SM", name: "San Marino" },
  "678": { alpha2: "ST", name: "Sao Tome and Principe" },
  "682": { alpha2: "SA", name: "Saudi Arabia" },
  "686": { alpha2: "SN", name: "Senegal" },
  "688": { alpha2: "RS", name: "Serbia" },
  "690": { alpha2: "SC", name: "Seychelles" },
  "694": { alpha2: "SL", name: "Sierra Leone" },
  "702": { alpha2: "SG", name: "Singapore" },
  "534": { alpha2: "SX", name: "Sint Maarten (Dutch part)" },
  "703": { alpha2: "SK", name: "Slovakia" },
  "705": { alpha2: "SI", name: "Slovenia" },
  "90": { alpha2: "SB", name: "Solomon Islands" },
  "706": { alpha2: "SO", name: "Somalia" },
  "710": { alpha2: "ZA", name: "South Africa" },
  "239": { alpha2: "GS", name: "South Georgia and the South Sandwich Islands" },
  "728": { alpha2: "SS", name: "South Sudan" },
  "724": { alpha2: "ES", name: "Spain" },
  "144": { alpha2: "LK", name: "Sri Lanka" },
  "729": { alpha2: "SD", name: "Sudan" },
  "740": { alpha2: "SR", name: "Suriname" },
  "744": { alpha2: "SJ", name: "Svalbard and Jan Mayen" },
  "752": { alpha2: "SE", name: "Sweden" },
  "756": { alpha2: "CH", name: "Switzerland" },
  "760": { alpha2: "SY", name: "Syrian Arab Republic" },
  "158": { alpha2: "TW", name: "Taiwan, Province of China" },
  "762": { alpha2: "TJ", name: "Tajikistan" },
  "834": { alpha2: "TZ", name: "Tanzania, United Republic of" },
  "764": { alpha2: "TH", name: "Thailand" },
  "626": { alpha2: "TL", name: "Timor-Leste" },
  "768": { alpha2: "TG", name: "Togo" },
  "772": { alpha2: "TK", name: "Tokelau" },
  "776": { alpha2: "TO", name: "Tonga" },
  "780": { alpha2: "TT", name: "Trinidad and Tobago" },
  "788": { alpha2: "TN", name: "Tunisia" },
  "792": { alpha2: "TR", name: "Turkey" },
  "795": { alpha2: "TM", name: "Turkmenistan" },
  "796": { alpha2: "TC", name: "Turks and Caicos Islands" },
  "798": { alpha2: "TV", name: "Tuvalu" },
  "800": { alpha2: "UG", name: "Uganda" },
  "804": { alpha2: "UA", name: "Ukraine" },
  "784": { alpha2: "AE", name: "United Arab Emirates" },
  "826": { alpha2: "GB", name: "United Kingdom of Great Britain and Northern Ireland" },
  "840": { alpha2: "US", name: "United States of America" },
  "581": { alpha2: "UM", name: "United States Minor Outlying Islands" },
  "858": { alpha2: "UY", name: "Uruguay" },
  "860": { alpha2: "UZ", name: "Uzbekistan" },
  "548": { alpha2: "VU", name: "Vanuatu" },
  "862": { alpha2: "VE", name: "Venezuela (Bolivarian Republic of)" },
  "704": { alpha2: "VN", name: "Viet Nam" },
  "92": { alpha2: "VG", name: "Virgin Islands (British)" },
  "850": { alpha2: "VI", name: "Virgin Islands (U.S.)" },
  "876": { alpha2: "WF", name: "Wallis and Futuna" },
  "732": { alpha2: "EH", name: "Western Sahara" },
  "887": { alpha2: "YE", name: "Yemen" },
  "894": { alpha2: "ZM", name: "Zambia" },
  "716": { alpha2: "ZW", name: "Zimbabwe" },
};