#####################################          __      __  _____  ____  ___
#                                   #         /  \    /  \/  _  \ \   \/  /
#     Blacklusion Pager Config      #         \   \/\/   /  /_\  \ \     /
#       Happy monitoring :)         #          \        /    |    \/     \
#                                   #           \__/\  /\____|__  /___/\  \
#####################################                \/         \/      \_/

[general]
    # Internal use only. Will not be seen by potential telegram subscribers
    name = 'wax-pager'

    # Logger Settings: silly, trace, debug, info, warn, error, fatal (default = info)
    logging_level = "info"

    # If set to false the validationCore will not try to contact the public telegram service (default: true)
    # Useful for analytic purposes without telegram notifications
    pager_mode = true

[telegram]
    # Public Blacklusion Pager Telegram service (accessible for the user)
    public_url = 'urlhere'

    # Private Telegram service (used for reporting errors to administrator)
    private_url = 'urlhere'

[chains]
    [mainnet]
    name = 'wax'
    chain_id = '1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4'
    api_endpoint = 'urlhere'
    server_versions = ["v2.0.5wax01", "v2.0.6wax02", "v2.0.7wax01", "v2.0.8wax01"]
    history_test_transaction = 'f383a4de1236fb6bc34f6dda26c5c552deca19844f5d27238de52873828e51c6'
    history_test_public_key = 'EOS77nEvHodDA2yWerxc4rw5WY6cY5j21WB7e76oZYjdRb6DMDN5d'
    api_test_big_block = 7846307
    api_test_big_bock_transaction_count = 76
    api_currency_symbol = "WAX"
    api_test_account = "blacklusionx"

    [testnet]
    name = 'wax-testnet'
    chain_id = 'f16b1833c747c43682f4386fca9cbb327929334a762755ebec17f6f23c9b8a12'
    api_endpoint = 'urlhere'
    server_versions = ["v2.0.5wax01", "v2.0.6wax02", "v2.0.7wax01", "v2.0.8wax01"]
    history_test_transaction = '1eadbd3a4db9fab95b3c2ebc8646e48f4b6a50934f6d3565cf4aeee426d9ec56'
    history_test_public_key = 'EOS5jjiP7AQvxV4vqHgSJLVdNxwtogYwhsvACLCA3XDwHWYzMtftY'
    api_currency_symbol = "WAX"
    api_test_account = "nation.wax"

# Validation Settings
[validation]
    # If a request fails, it will be retried x times (this value may be overwritten by requests are suppose to fail)
    request_retry_count = 4
    # Pause between retry of failed requests
    request_retry_pause_ms = 2500
    # Request will be canceled after x ms
    request_timeout_ms = 7000
    # Offset of getProducers request => max. x producers will be tracked in database
    producer_limit = 500
    p2p_block_count = 10
    p2p_ok_speed = 2
    api_head_bock_time_delta = 10000
    history_transaction_offset = 100
    history_actions_block_time_delta = 7200000
    hyperion_query_time_ms = 400
    # Valid social services in bp.json
    social_services = ["facebook", "github", "keybase", "reddit", "steemit", "telegram", "twitter", "wechat", "youtube", "medium", "hive"]

# Database connection configuration
[database]
    postgres_host = "localhost"
    postgres_port = 5432
    postgres_user = 'uniqueNameHere'
    postgres_password = 'uniquePasswordHere'
    postgres_db = 'wax_pager'